baseURL = "https://wreedb.github.io/"
languageCode = "en-us"
title = "Will Reed: Developer"
defaultContentLanguage = "en-us"
enableEmoji = true
theme = "hugo-blog-awesome"

[author]
  name = "Will Reed"
  email = "wreedb@disroot.org"

[module]
  [[module.imports]]
    path = 'github.com/hugo-sid/hugo-blog-awesome'

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params]
  sitename = "Will Reed: Developer"
  defaultColor = "dark"
  description = "A blog for my thoughts"
  mainSections = ['posts']
  toc = false
  goToTop = true

[params.author]
  avatar = "avatar.jpg"
  name = "Will Reed"
  email = "wreedb@disroot.org"
  intro = "Welcome to my blog"
  description = "A developer, GNU enthusiast, libre software advocate, init system surgeon and loser"

[[params.socialIcons]]
name = "github"
url = "https://github.com/wreedb"

[[params.socialIcons]]
name = "bluesky"
url = "https://bsky.app/profile/wreedb.bsky.social"

[[params.socialIcons]]
name = "youtube"
url = "https://youtube.com/@wreedb"

[[params.socialIcons]]
name = "discord"
url = "https://discord.com/users/586754734476623904"

[[params.socialIcons]]
name = "codeberg"
url = "https://codeberg.org/wreedb"

[menu]
  [[menu.main]]
    name = 'Home'
    url = '/'
    weight = 10
  [[menu.main]]
    name = 'God'
    url = '/god/'
  [[menu.main]]
    name = 'Confidant'
    url = '/confidant/'
  [[menu.main]]
    name = 'Posts'
    url = '/posts/'
    weight = 20
  [[menu.main]]
    name = 'About'
    url = '/about/'
    weight = 30
  [[menu.main]]
    name = 'PGP'
    url = '/pgp/'
    weight = 40